[theme.ui]
filters_show_count = true

[theme.ui.table]
show_separator = true
compact = false

[theme.colors.text]
primary = "#cdcecf"
secondary = "#71839b"
inverted = "#192330"
faint = "#304357"
warning = "#dbc074"
success = "#81b29a"
error = "#c94f6d"
actor = "#719cd6"

[theme.colors.background]
selected = "#29394f"

[theme.colors.border]
primary = "#304357"
secondary = "#29394f"
faint = "#192330"

[theme.colors.icon]
newcontributor = "#dbc074"
contributor = "#81b29a"
collaborator = "#719cd6"
member = "#9d79d6"
owner = "#f4a261"
unknownrole = "#71839b"

[theme.colors.pill]
draft_bg  = "#71839b"
open_bg   = "#81b29a"
closed_bg = "#c94f6d"
merged_bg = "#719cd6"
fg        = "#192330"
branch    = "#cdcecf"
author    = "#719cd6"
age       = "#71839b"
role      = "#71839b"
separator = "#71839b"

[theme.colors.footer]
prs           = "#719cd6"
issues        = "#81b29a"
notifications = "#9d79d6"
repo          = "#63cdcf"

[theme.colors.markdown]
text = "#cdcecf"
heading = "#719cd6"
h1 = "#c94f6d"
h2 = "#f4a261"
h3 = "#dbc074"
h4 = "#81b29a"
h5 = "#719cd6"
h6 = "#9d79d6"
code = "#d67ad2"
code_block = "#29394f"
link = "#63cdcf"
link_text = "#719cd6"
image = "#63cdcf"
image_text = "#81b29a"
horizontal_rule = "#304357"
strikethrough = "#304357"
emph = "#d67ad2"
strong = "#f4a261"

[theme.colors.markdown.syntax]
text = "#cdcecf"
background = "#192330"
error = "#c94f6d"
error_background = "#29394f"
comment = "#71839b"
comment_preproc = "#81b29a"
keyword = "#9d79d6"
keyword_reserved = "#c94f6d"
keyword_namespace = "#719cd6"
keyword_type = "#dbc074"
operator = "#63cdcf"
punctuation = "#cdcecf"
name = "#cdcecf"
name_builtin = "#63cdcf"
name_tag = "#c94f6d"
name_attribute = "#dbc074"
name_class = "#dbc074"
name_decorator = "#d67ad2"
name_function = "#719cd6"
number = "#f4a261"
string = "#81b29a"
string_escape = "#d67ad2"
deleted = "#c94f6d"
inserted = "#81b29a"
subheading = "#f4a261"

[theme.icons]
preset = "unicode"
