[theme.ui]
filters_show_count = true

[theme.ui.table]
show_separator = true
compact = false

[theme.colors.text]
primary = "#d6deeb"
secondary = "#637777"
inverted = "#011627"
faint = "#1d3b53"
warning = "#ffeb95"
success = "#addb67"
error = "#ff2c83"
actor = "#82aaff"
role = "#637777"

[theme.colors.background]
selected = "#1d3b53"

[theme.colors.border]
primary = "#637777"
secondary = "#1d3b53"
faint = "#011627"

[theme.colors.icon]
newcontributor = "#ffeb95"
contributor = "#addb67"
collaborator = "#82aaff"
member = "#c792ea"
owner = "#f78c6c"
unknownrole = "#637777"

[theme.colors.pill]
draft_bg  = "#637777"
open_bg   = "#addb67"
closed_bg = "#ff2c83"
merged_bg = "#82aaff"
fg        = "#011627"
branch    = "#d6deeb"
author    = "#82aaff"
age       = "#637777"
separator = "#637777"

[theme.colors.footer]
prs           = "#82aaff"
issues        = "#addb67"
notifications = "#c792ea"
repo          = "#7fdbca"

[theme.colors.markdown]
text = "#d6deeb"
heading = "#82aaff"
h1 = "#ff2c83"
h2 = "#f78c6c"
h3 = "#ffeb95"
h4 = "#addb67"
h5 = "#82aaff"
h6 = "#c792ea"
code = "#ff2c83"
code_block = "#1d3b53"
link = "#7fdbca"
link_text = "#82aaff"
image = "#7fdbca"
image_text = "#addb67"
horizontal_rule = "#637777"
strikethrough = "#637777"
emph = "#ff2c83"
strong = "#f78c6c"

[theme.colors.markdown.syntax]
text = "#d6deeb"
background = "#011627"
error = "#ff2c83"
error_background = "#1d3b53"
comment = "#637777"
comment_preproc = "#addb67"
keyword = "#c792ea"
keyword_reserved = "#ff2c83"
keyword_namespace = "#82aaff"
keyword_type = "#ffeb95"
operator = "#7fdbca"
punctuation = "#d6deeb"
name = "#d6deeb"
name_builtin = "#7fdbca"
name_tag = "#ff2c83"
name_attribute = "#ffeb95"
name_class = "#ffeb95"
name_decorator = "#c792ea"
name_function = "#82aaff"
number = "#f78c6c"
string = "#addb67"
string_escape = "#c792ea"
deleted = "#ff2c83"
inserted = "#addb67"
subheading = "#f78c6c"

[theme.icons]
preset = "unicode"
