[theme.ui]
filters_show_count = true

[theme.ui.table]
show_separator = true
compact = false

[theme.colors.text]
primary = "11"
secondary = "14"
inverted = "15"
faint = "12"
warning = "3"
success = "2"
error = "1"
actor = "4"
role = "14"

[theme.colors.background]
selected = "7"

[theme.colors.border]
primary = "14"
secondary = "7"
faint = "15"

[theme.colors.icon]
newcontributor = "3"
contributor = "2"
collaborator = "4"
member = "13"
owner = "9"
unknownrole = "14"

[theme.colors.pill]
draft_bg  = "12"
open_bg   = "2"
closed_bg = "1"
merged_bg = "4"
fg        = "15"
branch    = "11"
author    = "4"
age       = "14"
separator = "14"

[theme.colors.footer]
prs           = "4"
issues        = "2"
notifications = "5"
repo          = "13"
actions       = "9"

[theme.colors.markdown]
text = "11"
heading = "4"
h1 = "1"
h2 = "9"
h3 = "3"
h4 = "2"
h5 = "4"
h6 = "13"
code = "5"
code_block = "14"
link = "6"
link_text = "4"
image = "6"
image_text = "2"
horizontal_rule = "14"
strikethrough = "14"
emph = "5"
strong = "9"

[theme.colors.markdown.syntax]
text = "11"
background = "15"
error = "1"
error_background = "7"
comment = "14"
comment_preproc = "2"
keyword = "13"
keyword_reserved = "1"
keyword_namespace = "4"
keyword_type = "3"
operator = "6"
punctuation = "11"
name = "11"
name_builtin = "5"
name_tag = "4"
name_attribute = "3"
name_class = "3"
name_decorator = "5"
name_function = "4"
number = "9"
string = "2"
string_escape = "5"
deleted = "1"
inserted = "2"
subheading = "9"

[theme.icons]
preset = "ascii"
